apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sip
  name: vault-initiator
rules:
  # "" = core
  - apiGroups:
      - ""
    resources:
      - secrets
    # User "system:serviceaccount:sip:vault-initiator" cannot create resource "secrets" in API group "" in the namespace "sip"
#    resourceNames:
#      - vault-unseal-key
#      - vault-root-token
    verbs:
      - create
      - get
      - update
      - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-initiator
  namespace: sip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-create-secrets
  namespace: sip
subjects:
  - kind: ServiceAccount
    name: vault-initiator
    namespace: sip
roleRef:
  kind: Role
  name: vault-initiator
  apiGroup: rbac.authorization.k8s.io