apiVersion: batch/v1
kind: Job
metadata:
  name: vault-pki-server-authn
  namespace: sip
spec:
  template:
    spec:
      serviceAccountName: vault-initiator
      containers:
        - name: vault-pki-server-authn
          image: yukanyan/vault-pki-server-authn:v1.1.0
      restartPolicy: Never
  backoffLimit: 4