---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-sip-sec-com-v1alpha1-internalcertificate
  failurePolicy: Fail
  name: minternalcertificate.kb.io
  rules:
  - apiGroups:
    - sip.sec.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - internalcertificates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sip-sec-com-v1alpha1-internalcertificate
  failurePolicy: Fail
  name: vinternalcertificate.kb.io
  rules:
  - apiGroups:
    - sip.sec.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - internalcertificates
  sideEffects: None
