# Default values for Service-Identity-Provider.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sip:
  intcert:
    image: yukanyan/sip-intcert
    tag: v1.1.1
  intclica:
    image: yukanyan/sip-intclica
    tag: v1.1.0

vault_bootstrap:
  image: yukanyan/vault-bootstrap
  tag: v1.1.5
  env:
    VAULT_K8S_NAMESPACE: "sip"
    K8S_CLUSTER_NAME: "cluster.local"

vault_init:
  image: yukanyan/vault-init
  tag: v1.3.18
  env:
    VAULT_CLUSTER: "vault-0,vault-1,vault-2"
    K8S_CLUSTER_NAME: "cluster.local"

vault_pki:
  image: yukanyan/vault-pki-server-authn
  tag: v1.1.3

vault:
  enabled: true
  fullnameOverride: vault
  global:
    tlsDisable: false
  injector:
    enabled: true
  server:
    extraEnvironmentVars:
      VAULT_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      VAULT_TLSCERT: /vault/userconfig/vault-ha-tls/vault.crt
      VAULT_TLSKEY: /vault/userconfig/vault-ha-tls/vault.key
    volumes:
    - name: userconfig-vault-ha-tls
      secret:
        defaultMode: 420
        secretName: vault-ha-tls
    volumeMounts:
    - mountPath: /vault/userconfig/vault-ha-tls
      name: userconfig-vault-ha-tls
      readOnly: true
    dataStorage:
      enabled: true
      size: 1Gi
    auditStorage:
      enabled: false
      size: 1Gi
    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          cluster_name = "vault-for-sip"

          ui = true

          listener "tcp" {
              tls_disable = 0
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
              tls_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
              tls_client_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              
          }

          storage "raft" {
              path = "/vault/data"
          
              retry_join {
                leader_api_addr = "https://vault-active:8200"
                leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
                leader_client_key_file = "/vault/userconfig/vault-ha-tls/vault.key"
                leader_ca_cert_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              }
          }

          disable_mlock = true

          service_registration "kubernetes" {}

# certm:
#   enabled: true
#   fullnameOverride: certm
#   namespace: cert-managerr
#   crds:
#     enabled: true
