---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sip.sec.com
  resources:
  - internalclientcas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sip.sec.com
  resources:
  - internalclientcas/finalizers
  verbs:
  - update
- apiGroups:
  - sip.sec.com
  resources:
  - internalclientcas/status
  verbs:
  - get
  - patch
  - update
